{
 "title": "Log Dashboards",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "year", "label": "Year", "query": "2021, 2022,2023" },
   {
    "name": "month",
    "label": "Month",
    "query": "01,02,03,04,05,06,07,08,09,10,11,12"
   },
   {
    "name": "startday",
    "label": "Start Day",
    "query": "01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31"
   },
   {
    "name": "endday",
    "label": "End Day",
    "query": "01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31"
   },
   { "name": "method", "label": "HTTP Method", "query": "GET, PUT, POST" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests within Interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(requests_total{timestamp=~\"$year-$month-$endday.*\", http_method=~\"$method\"})-sum(requests_total{timestamp=~\"$year-$month-$endday.*\", http_method=~\"$method\"})",
     "legendFormat": "$year-$month-$startday - $year-$month-$endday"
    }
   ]
  },
  {
   "title": "Region Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "count by (location) (requests_total)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Microservice Usage Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "count by (microservice) (requests_total)",
     "legendFormat": "{{microservice}}"
    }
   ]
  },
  {
   "title": "Client Side Error Distribution by Regions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count by (location) (requests_total{status=~\"4.*\"})",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Server Side Errors Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    { "expr": "(rate(error_requests[5m]))", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "HTTP Method Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(requests_total{http_method=\"POST\"})",
     "legendFormat": "POST requests"
    },
    {
     "expr": "sum(requests_total{http_method=\"GET\"})",
     "legendFormat": "GET requests"
    },
    {
     "expr": "sum(requests_total{http_method=\"PUT\"})",
     "legendFormat": "PUT requests"
    }
   ]
  },
  {
   "title": "Message Type Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "count by (mssg_type) (requests_total)",
     "legendFormat": "{{mssg_type}}"
    }
   ]
  }
 ]
}